workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "dev"'

stages:
  - lint
  - build
  - test
  - deploy

pylint:
  stage: lint
  image: python:3.12.13-slim
  tags: [linting]
  before_script:
    - |
      if [ -f "mission-apprentissage/pyproject.toml" ] && grep -q "\[build-system\]" mission-apprentissage/pyproject.toml; then
        echo "Python project detected"
        python -m venv .venv
        source .venv/bin/activate
        pip install -e mission-apprentissage/.
      else
        echo "No known Python package management detected, creating a virtual environment"
        python -m venv .venv
        source .venv/bin/activate
      fi
      pip install pylint-gitlab==2.1.1
  script:
    - pylint --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find mission-apprentissage -type f -name "*.py" ! -path "*/.venv/*") > gl-code-quality-report.json
  artifacts:
    when: always
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  rules:
    - if: $CODE_QUALITY_DISABLED
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      exists:
        - "mission-apprentissage/**/*.py"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      exists:
        - "mission-apprentissage/**/*.py"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
      exists:
        - "mission-apprentissage/**/*.py"
  allow_failure: true

.docker-build-template:
  stage: build
  image: docker:latest
  tags: [docker]
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    COMPOSE_PROJECT_NAME: mission-apprentissage
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cp $ENV_FILE mission-apprentissage/.env

docker-image-build-redis:
  extends: .docker-build-template
  script:
    - IMAGE_TAG=$([ "$CI_COMMIT_BRANCH" = "main" ] && echo "latest" || echo "$CI_COMMIT_BRANCH")
    - docker compose -f mission-apprentissage/docker-compose.yml build redis
    - docker tag mission-apprentissage-redis $CI_REGISTRY_IMAGE/redis:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/redis:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - mission-apprentissage/backend/redis/Dockerfile
        - mission-apprentissage/backend/redis/redis.conf

docker-image-build-salesforce:
  extends: .docker-build-template
  script:
    - IMAGE_TAG=$([ "$CI_COMMIT_BRANCH" = "main" ] && echo "latest" || echo "$CI_COMMIT_BRANCH")
    - docker compose -f mission-apprentissage/docker-compose.yml build saleforce_cpu_large
    - docker tag mission-apprentissage-saleforce_cpu_large $CI_REGISTRY_IMAGE/salesforce:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/salesforce:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - mission-apprentissage/backend/models/model1/**
        - mission-apprentissage/backend/utils/**

docker-image-build-florence2:
  extends: .docker-build-template
  script:
    - IMAGE_TAG=$([ "$CI_COMMIT_BRANCH" = "main" ] && echo "latest" || echo "$CI_COMMIT_BRANCH")
    - docker compose -f mission-apprentissage/docker-compose.yml build florence2_large
    - docker tag mission-apprentissage-florence2_large $CI_REGISTRY_IMAGE/florence2:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/florence2:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - mission-apprentissage/backend/models/model2/**
        - mission-apprentissage/backend/utils/**

docker-image-build-git:
  extends: .docker-build-template
  script:
    - IMAGE_TAG=$([ "$CI_COMMIT_BRANCH" = "main" ] && echo "latest" || echo "$CI_COMMIT_BRANCH")
    - docker compose -f mission-apprentissage/docker-compose.yml build git_large
    - docker tag mission-apprentissage-git_large $CI_REGISTRY_IMAGE/git:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/git:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - mission-apprentissage/backend/models/model3/**
        - mission-apprentissage/backend/utils/**

docker-image-build-backend:
  extends: .docker-build-template
  script:
    - IMAGE_TAG=$([ "$CI_COMMIT_BRANCH" = "main" ] && echo "latest" || echo "$CI_COMMIT_BRANCH")
    - docker compose -f mission-apprentissage/docker-compose.yml build fastapi worker-taskiq
    - docker tag mission-apprentissage-fastapi $CI_REGISTRY_IMAGE/fastapi:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/fastapi:$IMAGE_TAG
    - docker tag mission-apprentissage-worker-taskiq $CI_REGISTRY_IMAGE/worker-taskiq:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/worker-taskiq:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - mission-apprentissage/pyproject.toml
        - mission-apprentissage/backend/**

docker-image-build-frontend:
  extends: .docker-build-template
  script:
    - IMAGE_TAG=$([ "$CI_COMMIT_BRANCH" = "main" ] && echo "latest" || echo "$CI_COMMIT_BRANCH")
    - docker compose -f mission-apprentissage/docker-compose.yml build frontend-django
    - docker tag mission-apprentissage-frontend-django $CI_REGISTRY_IMAGE/frontend-django:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/frontend-django:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      changes:
        - mission-apprentissage/pyproject.toml
        - mission-apprentissage/django_app/**

deploy-production:
  stage: deploy
  image: alpine:latest
  tags: [docker]
  script:
    - echo "Deploying application..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual