variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - deploy

docker-compose-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose -f mission-apprentissage/docker-compose.yml build
    - docker images
  only:
    - main
    - dev

deploy-production:
  stage: deploy
  script:
    - echo "Deploying application..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual