services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/redis/Dockerfile
    ports:
      - "6379:6379"
  saleforce_cpu_large:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/models/model1/Dockerfile
    ports:
      - "8001:8000"
  florence2_large:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/models/model2/Dockerfile
    ports:
      - "8002:8000"
  git_large:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/models/model3/Dockerfile
    ports:
      - "8003:8000"
  fastapi:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379/1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgresql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      UPLOAD_TEMP_DIR: /tmp/epub_shared
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      URL_SALESFORCE_CPU_LARGE: http://saleforce_cpu_large:8000/describe
      URL_FLORANCE_2_LARGE: http://florence2_large:8000/describe
      URL_GIT_LARGE: http://git_large:8000/describe
      BATCH_SIZE: ${BATCH_SIZE}
      BATCH_MAX: ${BATCH_MAX}
    volumes:
      - epub_shared:/tmp/epub_shared
    depends_on:
      - redis
      - postgresql
  worker-taskiq:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/worker/Dockerfile
    environment:
      REDIS_URL: redis://redis:6379/1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgresql
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      UPLOAD_TEMP_DIR: /tmp/epub_shared
      URL_SALESFORCE_CPU_LARGE: http://saleforce_cpu_large:8000/describe
      URL_FLORANCE_2_LARGE: http://florence2_large:8000/describe
      URL_GIT_LARGE: http://git_large:8000/describe
      BATCH_SIZE: ${BATCH_SIZE}
      BATCH_MAX: ${BATCH_MAX}
    volumes:
      - epub_shared:/tmp/epub_shared
    depends_on:
      - redis
      - postgresql
  
  frontend-django:
    build:
      context: ..
      dockerfile: mission-apprentissage/django_app/Dockerfile
    ports:
      - "7001:7001"
    depends_on:
      - fastapi

volumes:
  epub_shared: