version: '3.9'
services:
  saleforce_cpu_large:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/models/model1/Dockerfile
    ports:
      - "8001:8000"
  florence2_large:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/models/model2/Dockerfile
    ports:
      - "8002:8000"
  git_large:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/models/model3/Dockerfile
    ports:
      - "8003:8000"
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    build:
      context: ..
      dockerfile: mission-apprentissage/backend/redis/Dockerfile
    ports:
      - "6380:6379"