# Port Redis par défaut
port 6379

# Permet d’accepter les connexions depuis l’extérieur du conteneur.
bind 0.0.0.0

# Configuration de la persistance des données
save 900 1
save 300 10
save 60 10000

# Emplacement des fichiers de données
dir /data
dbfilename dump.rdb

# Désactiver le mode protégé (puisque nous nous lions à 0.0.0.0)
protected-mode no

# Optionnel : exiger un mot de passe
# requirepass monMotDePasse
