version: '3.9'
services:
  saleforce_cpu_large:
    build:
      context: ..
      dockerfile: models/model1/Dockerfile
    ports:
      - "8001:8000"
  florence2_large:
    build:
      context: ..
      dockerfile: models/model2/Dockerfile
    ports:
      - "8002:8000"
  git_large:
    build:
      context: ..
      dockerfile: models/model3/Dockerfile
    ports:
      - "8003:8000"