"""initialize database

Revision ID: 3e4a2bb83782
Revises: 
Create Date: 2026-02-23 11:30:56.150502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4a2bb83782'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ModelsIA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'Users', ['email'], unique=False)
    op.create_table('Tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id_redis', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='task_status'), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('processed_images', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id_redis')
    )
    op.create_index('idx_tasks_status', 'Tasks', ['status'], unique=False)
    op.create_index('idx_tasks_task_id_redis', 'Tasks', ['task_id_redis'], unique=False)
    op.create_table('Epubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='epub_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_epubs_task_id', 'Epubs', ['task_id'], unique=False)
    op.create_table('Images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('epub_id', sa.Integer(), nullable=False),
    sa.Column('image_file_name', sa.String(length=255), nullable=False),
    sa.Column('image_position_in_epub', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['epub_id'], ['Epubs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_images_epub_id', 'Images', ['epub_id'], unique=False)
    op.create_index('idx_images_task_id', 'Images', ['task_id'], unique=False)
    op.create_table('ImageDescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('model_ia_id', sa.Integer(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('is_written_by_ai', sa.Boolean(), nullable=False),
    sa.Column('is_written_by_human', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('validated_by_human', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['Images.id'], ),
    sa.ForeignKeyConstraint(['model_ia_id'], ['ModelsIA.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_descriptions_image_id', 'ImageDescriptions', ['image_id'], unique=False)
    op.create_index('idx_image_descriptions_is_written_by_ai', 'ImageDescriptions', ['is_written_by_ai'], unique=False)
    op.create_index('idx_image_descriptions_is_written_by_human', 'ImageDescriptions', ['is_written_by_human'], unique=False)
    op.create_index('idx_image_descriptions_model_ia_id', 'ImageDescriptions', ['model_ia_id'], unique=False)
    op.create_index('idx_image_model', 'ImageDescriptions', ['image_id', 'model_ia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_image_model', table_name='ImageDescriptions')
    op.drop_index('idx_image_descriptions_model_ia_id', table_name='ImageDescriptions')
    op.drop_index('idx_image_descriptions_is_written_by_human', table_name='ImageDescriptions')
    op.drop_index('idx_image_descriptions_is_written_by_ai', table_name='ImageDescriptions')
    op.drop_index('idx_image_descriptions_image_id', table_name='ImageDescriptions')
    op.drop_table('ImageDescriptions')
    op.drop_index('idx_images_task_id', table_name='Images')
    op.drop_index('idx_images_epub_id', table_name='Images')
    op.drop_table('Images')
    op.drop_index('idx_epubs_task_id', table_name='Epubs')
    op.drop_table('Epubs')
    op.drop_index('idx_tasks_task_id_redis', table_name='Tasks')
    op.drop_index('idx_tasks_status', table_name='Tasks')
    op.drop_table('Tasks')
    op.drop_index('idx_users_email', table_name='Users')
    op.drop_table('Users')
    op.drop_table('ModelsIA')
    # ### end Alembic commands ###
