"""add models name in the database

Revision ID: b54d066371af
Revises: 3e4a2bb83782
Create Date: 2026-02-23 15:29:16.643052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54d066371af'
down_revision: Union[str, Sequence[str], None] = '3e4a2bb83782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    models_ia = sa.table(
        "ModelsIA",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.TIMESTAMP),
        sa.column("updated_at", sa.TIMESTAMP),
    )

    op.execute(
        models_ia.insert().from_select(
            ["name", "is_active", "created_at", "updated_at"],
            sa.select(
                sa.literal("Salesforce BLIP"),
                sa.literal(True),
                sa.func.now(),
                sa.func.now(),
            ).where(
                ~sa.exists(sa.select(models_ia.c.id).where(models_ia.c.name == "Salesforce BLIP"))
            )
        )
    )

    op.execute(
        models_ia.insert().from_select(
            ["name", "is_active", "created_at", "updated_at"],
            sa.select(
                sa.literal("Florence-2"),
                sa.literal(True),
                sa.func.now(),
                sa.func.now(),
            ).where(
                ~sa.exists(sa.select(models_ia.c.id).where(models_ia.c.name == "Florence-2"))
            )
        )
    )

    op.execute(
        models_ia.insert().from_select(
            ["name", "is_active", "created_at", "updated_at"],
            sa.select(
                sa.literal("GIT Large"),
                sa.literal(True),
                sa.func.now(),
                sa.func.now(),
            ).where(
                ~sa.exists(sa.select(models_ia.c.id).where(models_ia.c.name == "GIT Large"))
            )
        )
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
