"""DROP column validated_by_human in DescriptionByIA

Revision ID: f2e6bfed00f2
Revises: af54b3df9281
Create Date: 2026-05-26 10:40:05.266764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e6bfed00f2'
down_revision: Union[str, Sequence[str], None] = 'af54b3df9281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DescriptionByIA', 'validated_by_human')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DescriptionByIA', sa.Column('validated_by_human', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
