"""Add of the images localisation to MinIO

Revision ID: 682d342ad907
Revises: f2e6bfed00f2
Create Date: 2026-06-29 13:58:05.195060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682d342ad907'
down_revision: Union[str, Sequence[str], None] = 'f2e6bfed00f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Images', sa.Column('storage_bucket', sa.String(length=255), nullable=True))
    op.add_column('Images', sa.Column('storage_object_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Images', 'storage_object_key')
    op.drop_column('Images', 'storage_bucket')
    # ### end Alembic commands ###
