"""add refresh tokens table

Revision ID: bf4038acc964
Revises: b54d066371af
Create Date: 2026-04-13 15:09:33.767487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf4038acc964"
down_revision: Union[str, Sequence[str], None] = "b54d066371af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "RefreshTokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index("idx_refresh_tokens_token", "RefreshTokens", ["token"], unique=False)
    op.create_index("idx_refresh_tokens_user_id", "RefreshTokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_refresh_tokens_user_id", table_name="RefreshTokens")
    op.drop_index("idx_refresh_tokens_token", table_name="RefreshTokens")
    op.drop_table("RefreshTokens")
    # ### end Alembic commands ###
