name: Generate changelog
on:
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@master
        with:
          REPO_NAME: "studio-paon-avh/desc-image-ia"
          ACCESS_TOKEN: ${{secrets.SECRET_TOKEN}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs(CHANGELOG): update release notes"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements"